const testSheet = {
  name: "Test",
  author: "John Doe",
  timeSignature: [4, 4],
  items: [
    { type: "note", name: "do", value: 1 / 16, dotted: true },
    { type: "note", name: "re", value: 1 / 16 },
    { type: "note", name: "mi", value: 1 / 16 },
    { type: "note", name: "fa", value: 1 / 16 },
    { type: "note", name: "fa#", value: 1 / 16 },
    { type: "note", name: "sol", value: 1 / 16 },
    { type: "note", name: "la", value: 1 / 16 },
    { type: "note", name: "si", value: 1 / 16, dotted: true },
    { type: "note", name: "do'", value: 1 / 16 },
    { type: "note", name: "re'", value: 1 / 16 },
    { type: "note", name: "mi'", value: 1 / 16 },

    { type: "note", name: "do", value: 1 / 8, dotted: true },
    { type: "note", name: "re", value: 1 / 8 },
    { type: "note", name: "mi", value: 1 / 8 },
    { type: "note", name: "fa", value: 1 / 8 },
    { type: "note", name: "fa#", value: 1 / 8 },
    { type: "note", name: "sol", value: 1 / 8 },
    { type: "note", name: "la", value: 1 / 4 },
    { type: "note", name: "si", value: 1 / 8, dotted: true },
    { type: "note", name: "do'", value: 1 / 8 },
    { type: "note", name: "re'", value: 1 / 8 },
    { type: "note", name: "mi'", value: 1 / 8 },

    { type: "note", name: "do", value: 1 / 4, dotted: true },
    { type: "note", name: "re", value: 1 / 4 },
    { type: "note", name: "mi", value: 1 / 4 },
    { type: "note", name: "fa", value: 1 / 4 },
    { type: "note", name: "fa#", value: 1 / 4 },
    { type: "note", name: "sol", value: 1 / 4, dotted: true },
    { type: "note", name: "la", value: 1 / 4 },
    { type: "note", name: "si", value: 1 / 4, dotted: true },
    { type: "note", name: "do'", value: 1 / 4, dotted: true },
    { type: "note", name: "re'", value: 1 / 4 },
    { type: "note", name: "mi'", value: 1 / 4 },

    { type: "note", name: "do", value: 1 / 2 },
    { type: "note", name: "re", value: 1 / 2 },
    { type: "note", name: "mi", value: 1 / 2, dotted: true },
    { type: "note", name: "fa", value: 1 / 2 },
    { type: "note", name: "fa#", value: 1 / 2 },
    { type: "note", name: "sol", value: 1 / 2, dotted: true },
    { type: "note", name: "la", value: 1 / 2 },
    { type: "note", name: "si", value: 1 / 2 },
    { type: "note", name: "do'", value: 1 / 2 },
    { type: "note", name: "re'", value: 1 / 2 },
    { type: "note", name: "mi'", value: 1 / 2, dotted: true },

    { type: "note", name: "do", value: 1, dotted: true },
    { type: "note", name: "re", value: 1, dotted: true },
    { type: "note", name: "mi", value: 1, dotted: true },
    { type: "note", name: "fa", value: 1, dotted: true },
    { type: "note", name: "fa#", value: 1, dotted: true },
    { type: "note", name: "sol", value: 1, dotted: true },
    { type: "note", name: "la", value: 1, dotted: true },
    { type: "note", name: "si", value: 1, dotted: true },
    { type: "note", name: "do'", value: 1, dotted: true },
    { type: "note", name: "re'", value: 1, dotted: true },
    { type: "note", name: "mi'", value: 1, dotted: true },

    { type: "rest", value: 1 },
    { type: "rest", value: 1 / 2 },
    { type: "rest", value: 1 / 4 },
    { type: "rest", value: 1 / 8 },

    { type: "note", name: "mi'", value: 1 / 8 },
    { type: "note", name: "mi'", value: 1 / 8, tied: "start" },
    { type: "note", name: "mi'", value: 1 / 8, tied: "end" },
    { type: "note", name: "mi'", value: 1 / 2, tied: "start" },
    { type: "note", name: "mi'", value: 1 / 2, tied: "end" },
    { type: "note", name: "mi'", value: 1 / 2 },
    { type: "note", name: "mi'", value: 1 / 16 },
    { type: "note", name: "mi'", value: 1 / 16 },
  ],
};

export default [
  ...(import.meta.env.MODE === "development" ? [testSheet] : []),
  {
    name: "La rumeur",
    author: "Manau",
    timeSignature: [4, 4],
    startValue: 0.5,
    items: [
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "si", value: 1 / 4, dotted: true },
      { type: "note", name: "si", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 4 },
      { type: "note", name: "do'", value: 1 / 4 },
      { type: "note", name: "si", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "la", value: 1 / 4 },
      { type: "note", name: "si", value: 1 / 2 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 4, dotted: true },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 2 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 },
    ],
  },
  {
    name: "Ensemble",
    author: "Jean-Jacques Goldman",
    timeSignature: [4, 4],
    items: [
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "re", value: 1 / 8, tied: "start" },
      { type: "note", name: "re", value: 1 / 2, tied: "end" },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 8, tied: "start" },
      { type: "note", name: "mi", value: 1 / 8, tied: "end" },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "do", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 4 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8, tied: "start" },
      { type: "note", name: "fa", value: 1 / 8, tied: "end" },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 8, tied: "start" },
      { type: "note", name: "mi", value: 1 / 8, tied: "end" },
      { type: "note", name: "la", value: 1 / 4 },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "si", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8, tied: "start" },
      { type: "note", name: "la", value: 1 / 8, tied: "end" },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8, tied: "start" },
      { type: "note", name: "la", value: 1 / 8, tied: "end" },
      { type: "note", name: "la", value: 1 / 4 },
      { type: "note", name: "la", value: 1 / 8, tied: "start" },
      { type: "note", name: "la", value: 1 / 8, tied: "end" },
      { type: "rest", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8, tied: "start" },
      { type: "note", name: "fa", value: 1 / 8, tied: "end" },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "rest", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "la", value: 1 / 8, tied: "start" },
      { type: "note", name: "la", value: 1 / 8, tied: "end" },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 8 },
    ],
  },
  {
    name: "Baby Shark",
    author: "Min Seok Kim",
    timeSignature: [4, 4],
    items: [
      { type: "note", name: "do", value: 1 / 4 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 16 },
      { type: "note", name: "fa", value: 1 / 16, tied: "start" },
      { type: "note", name: "fa", value: 1 / 16, tied: "end" },
      { type: "note", name: "fa", value: 1 / 16 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "do", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 16 },
      { type: "note", name: "fa", value: 1 / 16, tied: "start" },
      { type: "note", name: "fa", value: 1 / 16, tied: "end" },
      { type: "note", name: "fa", value: 1 / 16 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "do", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 16 },
      { type: "note", name: "fa", value: 1 / 16, tied: "start" },
      { type: "note", name: "fa", value: 1 / 16, tied: "end" },
      { type: "note", name: "fa", value: 1 / 16 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "fa", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "rest", value: 1 / 4 },
    ],
  },
  {
    name: "Joyeux anniversaire",
    author: "Robert Coleman",
    timeSignature: [3, 4],
    startValue: 0.5,
    items: [
      { type: "note", name: "re", value: 1 / 8, dotted: true },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "fa#", value: 1 / 2 },
      { type: "note", name: "re", value: 1 / 8, dotted: true },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "la", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 2 },
      { type: "note", name: "re", value: 1 / 8, dotted: true },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "re'", value: 1 / 4 },
      { type: "note", name: "si", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "fa#", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 2, tied: "start" },
      { type: "note", name: "mi", value: 1 / 4, tied: "end" },
      { type: "rest", value: 1 / 4 },
      { type: "note", name: "do'", value: 1 / 8, dotted: true },
      { type: "note", name: "do'", value: 1 / 16 },
      { type: "note", name: "si", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "la", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 2, dotted: true },
    ],
  },
  {
    name: "Concerning hobbits",
    author: "Howard Shore",
    timeSignature: [2, 4],
    items: [
      { type: "note", name: "do", value: 1 / 16 },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 8, tied: "start" },
      { type: "note", name: "sol", value: 1 / 8, tied: "end" },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "do", value: 1 / 2 },
      { type: "rest", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 4, dotted: true },
      { type: "note", name: "do'", value: 1 / 8 },
      { type: "note", name: "si", value: 1 / 4, dotted: true },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 4, dotted: true },
      { type: "note", name: "fa", value: 1 / 16 },
      { type: "note", name: "mi", value: 1 / 16 },
      { type: "note", name: "re", value: 1 / 4, dotted: true },
      { type: "note", name: "do", value: 1 / 16 },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "note", name: "do", value: 1 / 16 },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "do", value: 1 / 2 },
      { type: "rest", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "la", value: 1 / 2 },
      { type: "note", name: "sol", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 2 },
      { type: "note", name: "re", value: 1 / 2 },
      { type: "note", name: "do", value: 1 / 16 },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "do", value: 1 / 4, dotted: true },
      { type: "rest", value: 1 },
      { type: "rest", value: 1 },
      { type: "rest", value: 1 },
      { type: "note", name: "do", value: 1 / 16 },
      { type: "note", name: "re", value: 1 / 16 },
      { type: "note", name: "mi", value: 1 / 4, dotted: true },
      { type: "note", name: "mi", value: 1 / 4 },
      { type: "note", name: "mi", value: 1 / 8 },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "note", name: "do", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 8 },
      { type: "rest", value: 1 },
      { type: "note", name: "sol", value: 1 / 16 },
      { type: "note", name: "la", value: 1 / 16 },
      { type: "note", name: "si", value: 1 / 4, tied: "start" },
      { type: "note", name: "si", value: 1 / 8, tied: "end" },
      { type: "note", name: "si", value: 1 / 8 },
      { type: "note", name: "do'", value: 1 / 4 },
      { type: "note", name: "la", value: 1 / 8 },
      { type: "note", name: "mi", value: 1 / 4, dotted: true },
      { type: "note", name: "sol", value: 1 / 8 },
      { type: "note", name: "re", value: 1 / 4 },
      { type: "rest", value: 1 / 4 },
    ],
  },
];
