export default [
  {
    name: "Ensemble",
    author: "Jean-Jacques Goldman",
    bars: 4,
    notes: [
      { name: "re", value: "black" },
      { name: "re", value: "black" },
      { name: "re", value: "black" },
      { name: "re", value: "white" },
      { name: "fa", value: "black" },
      { name: "sol", value: "black" },
      { name: "fa", value: "black" },
      { name: "mi", value: "black" },
      { name: "mi", value: "black" },
      { name: "re", value: "black" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "la", value: "black" },
      { name: "re", value: "black" },
      { name: "fa", value: "black" },
      { name: "sol", value: "black" },
      { name: "fa", value: "black" },
      { name: "re", value: "black" },
      { name: "mi", value: "black" },
      { name: "la", value: "black" },
      { name: "re", value: "black" },
      { name: "si", value: "black" },
      { name: "la", value: "black" },
      { name: "sol", value: "black" },
      { name: "la", value: "black" },
      { name: "fa", value: "black" },
      { name: "sol", value: "black" },
      { name: "la", value: "black" },
      { name: "la", value: "black" },
      { name: "la", value: "black" },
      { name: "fa", value: "black" },
      { name: "la", value: "black" },
      { name: "sol", value: "black" },
      { name: "fa", value: "black" },
      { name: "mi", value: "black" },
      { name: "fa", value: "black" },
      { name: "re", value: "black" },
      { name: "mi", value: "black" },
      { name: "fa", value: "black" },
      { name: "re", value: "black" },
      { name: "la", value: "black" },
      { name: "sol", value: "black" },
      { name: "fa", value: "black" },
      { name: "mi", value: "black" },
    ],
  },
  {
    name: "Baby Shark",
    author: "Min Seok Kim",
    bars: 4,
    notes: [
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "fa", value: "black" },
      { name: "mi", value: "black" },
    ],
  },
  {
    name: "Joyeux anniversaire",
    author: "Robert Coleman",
    bars: 4,
    notes: [
      { name: "re", value: "black dotted" },
      { name: "re", value: "black" },
      { name: "mi", value: "black" },
      { name: "re", value: "black" },
      { name: "sol", value: "black" },
      { name: "fa#", value: "white" },
      { name: "re", value: "black dotted" },
      { name: "re", value: "black" },
      { name: "mi", value: "black" },
      { name: "re", value: "black" },
      { name: "la", value: "black" },
      { name: "sol", value: "white" },
      { name: "re", value: "black dotted" },
      { name: "re", value: "black" },
      { name: "re'", value: "black" },
      { name: "si", value: "black" },
      { name: "sol", value: "black" },
      { name: "fa#", value: "black" },
      { name: "mi", value: "white" },
      { name: "mi", value: "black" },
      { name: "do'", value: "black dotted" },
      { name: "do'", value: "black" },
      { name: "si", value: "black" },
      { name: "sol", value: "black" },
      { name: "la", value: "black" },
      { name: "sol", value: "white dotted" },
    ],
  },
  {
    name: "Concerning hobbits",
    author: "Howard Shore",
    bars: 4,
    notes: [
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "mi", value: "black" },
      { name: "sol", value: "black" },
      { name: "sol", value: "black" },
      { name: "mi", value: "black" },
      { name: "re", value: "black" },
      { name: "do", value: "white" },
      { name: "mi", value: "black" },
      { name: "sol", value: "black" },
      { name: "la", value: "black dotted" },
      { name: "do'", value: "black" },
      { name: "si", value: "black dotted" },
      { name: "sol", value: "black" },
      { name: "mi", value: "black dotted" },
      { name: "fa", value: "black" },
      { name: "mi", value: "black" },
      { name: "re", value: "black dotted" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "mi", value: "black" },
      { name: "sol", value: "black" },
      { name: "mi", value: "black" },
      { name: "re", value: "black" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "do", value: "white" },
      { name: "mi", value: "black" },
      { name: "sol", value: "black" },
      { name: "la", value: "white" },
      { name: "sol", value: "black" },
      { name: "mi", value: "black" },
      { name: "mi", value: "white" },
      { name: "re", value: "white" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "do", value: "black dotted" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "mi", value: "black dotted" },
      { name: "mi", value: "black" },
      { name: "mi", value: "black" },
      { name: "sol", value: "black" },
      { name: "re", value: "black" },
      { name: "do", value: "black" },
      { name: "re", value: "black" },
      { name: "sol", value: "black" },
      { name: "la", value: "black" },
      { name: "si", value: "black" },
      { name: "si", value: "black" },
      { name: "do'", value: "black" },
      { name: "la", value: "black" },
      { name: "mi", value: "black dotted" },
      { name: "sol", value: "black" },
      { name: "re", value: "black" },
    ],
  },
];
