const testSheet = {
  name: "Test",
  author: "John Doe",
  timeSignature: [4, 4],
  items: [
    { type: "note", name: "do", value: "sixteenth", dotted: true },
    { type: "note", name: "re", value: "sixteenth" },
    { type: "note", name: "mi", value: "sixteenth" },
    { type: "note", name: "fa", value: "sixteenth" },
    { type: "note", name: "fa", value: "sixteenth", sharp: true },
    { type: "note", name: "sol", value: "sixteenth" },
    { type: "note", name: "la", value: "sixteenth" },
    { type: "note", name: "si", value: "sixteenth", dotted: true },
    { type: "note", name: "do'", value: "sixteenth" },
    { type: "note", name: "re'", value: "sixteenth" },
    { type: "note", name: "mi'", value: "sixteenth" },
    { type: "note", name: "fa'", value: "sixteenth" },

    { type: "note", name: "do", value: "eighth", dotted: true },
    { type: "note", name: "re", value: "eighth" },
    { type: "note", name: "mi", value: "eighth" },
    { type: "note", name: "fa", value: "eighth" },
    { type: "note", name: "fa", value: "eighth", sharp: true },
    { type: "note", name: "sol", value: "eighth" },
    { type: "note", name: "la", value: "quarter" },
    { type: "note", name: "si", value: "eighth", dotted: true },
    { type: "note", name: "do'", value: "eighth" },
    { type: "note", name: "re'", value: "eighth" },
    { type: "note", name: "mi'", value: "eighth" },
    { type: "note", name: "fa'", value: "eighth" },

    { type: "note", name: "do", value: "quarter", dotted: true },
    { type: "note", name: "re", value: "quarter" },
    { type: "note", name: "mi", value: "quarter" },
    { type: "note", name: "fa", value: "quarter" },
    { type: "note", name: "fa", value: "quarter", sharp: true },
    { type: "note", name: "sol", value: "quarter", dotted: true },
    { type: "note", name: "la", value: "quarter" },
    { type: "note", name: "si", value: "quarter", dotted: true },
    { type: "note", name: "do'", value: "quarter", dotted: true },
    { type: "note", name: "re'", value: "quarter" },
    { type: "note", name: "mi'", value: "quarter" },
    { type: "note", name: "fa'", value: "quarter" },

    { type: "note", name: "do", value: "half" },
    { type: "note", name: "re", value: "half" },
    { type: "note", name: "mi", value: "half", dotted: true },
    { type: "note", name: "fa", value: "half" },
    { type: "note", name: "fa", value: "half", sharp: true },
    { type: "note", name: "sol", value: "half", dotted: true },
    { type: "note", name: "la", value: "half" },
    { type: "note", name: "si", value: "half" },
    { type: "note", name: "do'", value: "half" },
    { type: "note", name: "re'", value: "half" },
    { type: "note", name: "mi'", value: "half", dotted: true },
    { type: "note", name: "fa'", value: "half", dotted: true },

    { type: "note", name: "do", value: "whole", dotted: true },
    { type: "note", name: "re", value: "whole", dotted: true },
    { type: "note", name: "mi", value: "whole", dotted: true },
    { type: "note", name: "fa", value: "whole", dotted: true },
    { type: "note", name: "fa", value: "whole", dotted: true, sharp: true },
    { type: "note", name: "sol", value: "whole", dotted: true },
    { type: "note", name: "la", value: "whole", dotted: true },
    { type: "note", name: "si", value: "whole", dotted: true },
    { type: "note", name: "do'", value: "whole", dotted: true },
    { type: "note", name: "re'", value: "whole", dotted: true },
    { type: "note", name: "mi'", value: "whole", dotted: true },
    { type: "note", name: "fa'", value: "whole", dotted: true },

    { type: "rest", value: "whole" },
    { type: "rest", value: "half" },
    { type: "rest", value: "quarter" },
    { type: "rest", value: "eighth" },

    { type: "note", name: "mi'", value: "eighth" },
    { type: "note", name: "mi'", value: "eighth", tied: "start" },
    { type: "note", name: "mi'", value: "eighth", tied: "end" },
    { type: "note", name: "mi'", value: "half", tied: "start" },
    { type: "note", name: "mi'", value: "half", tied: "end" },
    { type: "note", name: "mi'", value: "half" },
    { type: "note", name: "mi'", value: "sixteenth" },
    { type: "note", name: "mi'", value: "sixteenth" },
    { type: "note", name: "fa'", value: "sixteenth" },

    { type: "note", name: "si", value: "quarter", flat: true },
    { type: "note", name: "fa", value: "quarter", sharp: true },
  ],
};

export default [
  ...(import.meta.env.MODE === "development" ? [testSheet] : []),
  {
    name: "La rumeur",
    author: "Manau",
    timeSignature: [4, 4],
    startValue: 0.5,
    items: [
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "si", value: "quarter", dotted: true },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "si", value: "half" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "fa", value: "quarter", dotted: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "mi", value: "whole" },
    ],
  },
  {
    name: "Ensemble",
    author: "Jean-Jacques Goldman",
    timeSignature: [4, 4],
    items: [
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "re", value: "eighth", tied: "start" },
      { type: "note", name: "re", value: "half", tied: "end" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "eighth", tied: "start" },
      { type: "note", name: "mi", value: "eighth", tied: "end" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "fa", value: "eighth", tied: "start" },
      { type: "note", name: "fa", value: "eighth", tied: "end" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "mi", value: "eighth", tied: "start" },
      { type: "note", name: "mi", value: "eighth", tied: "end" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "la", value: "eighth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth", tied: "start" },
      { type: "note", name: "fa", value: "eighth", tied: "end" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "la", value: "eighth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
    ],
  },
  {
    name: "Baby Shark",
    author: "Min Seok Kim",
    timeSignature: [4, 4],
    items: [
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "fa", value: "sixteenth", tied: "start" },
      { type: "note", name: "fa", value: "sixteenth", tied: "end" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "fa", value: "sixteenth", tied: "start" },
      { type: "note", name: "fa", value: "sixteenth", tied: "end" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "fa", value: "sixteenth", tied: "start" },
      { type: "note", name: "fa", value: "sixteenth", tied: "end" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "rest", value: "quarter" },
    ],
  },
  {
    name: "Joyeux anniversaire",
    author: "Robert Coleman",
    timeSignature: [3, 4],
    startValue: 0.5,
    items: [
      { type: "note", name: "re", value: "eighth", dotted: true },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "half", sharp: true },
      { type: "note", name: "re", value: "eighth", dotted: true },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "re", value: "eighth", dotted: true },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter", sharp: true },
      { type: "note", name: "mi", value: "half", tied: "start" },
      { type: "note", name: "mi", value: "quarter", tied: "end" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "do'", value: "eighth", dotted: true },
      { type: "note", name: "do'", value: "sixteenth" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "half", dotted: true },
    ],
  },
  // Source: https://www.youtube.com/watch?v=GrUunXxXQ8I&t=72s
  {
    name: "Concerning hobbits",
    author: "Howard Shore",
    timeSignature: [2, 4],
    items: [
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "eighth", tied: "end" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "do", value: "half" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "quarter", dotted: true },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "si", value: "quarter", dotted: true },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "quarter", dotted: true },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "re", value: "quarter", dotted: true },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "do", value: "half" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "half" },
      { type: "note", name: "re", value: "half" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "do", value: "quarter", dotted: true },
      { type: "rest", value: "whole" },
      { type: "rest", value: "whole" },
      { type: "rest", value: "whole" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "quarter", dotted: true },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "rest", value: "whole" },
      { type: "note", name: "sol", value: "sixteenth" },
      { type: "note", name: "la", value: "sixteenth" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "si", value: "eighth", tied: "start" },
      { type: "note", name: "si", value: "eighth", tied: "end" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "mi", value: "quarter", dotted: true },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "rest", value: "quarter" },
      { type: "rest", value: "half" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "quarter", dotted: true },
      { type: "rest", value: "eighth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "re", value: "eighth", tied: "start" },
      { type: "note", name: "re", value: "quarter", dotted: true, tied: "end" },
      { type: "note", name: "do'", value: "sixteenth" },
      { type: "note", name: "si", value: "sixteenth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "mi'", value: "quarter", dotted: true },
      { type: "rest", value: "quarter" },
      { type: "rest", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "la", value: "sixteenth" },
      { type: "note", name: "si", value: "sixteenth" },
      { type: "note", name: "do'", value: "quarter", dotted: true },
      { type: "note", name: "si", value: "eighth", tied: "start" },
      { type: "note", name: "si", value: "quarter", dotted: true, tied: "end" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "quarter", dotted: true },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "re", value: "quarter", dotted: true },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "half" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "re", value: "half" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "quarter", dotted: true },
      { type: "rest", value: "eighth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "mi", value: "half" },
      { type: "note", name: "re", value: "half" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "do", value: "quarter", dotted: true },
    ],
  },
  {
    name: "The Office Theme",
    author: "Daniel Tidwell",
    timeSignature: [4, 4],
    items: [
      { type: "rest", value: "quarter" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "do'", value: "half", tied: "start" },
      { type: "note", name: "do'", value: "half", tied: "end" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "half", dotted: true },
      { type: "rest", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "do", value: "half" },
      { type: "note", name: "do'", value: "half", tied: "start" },
      { type: "note", name: "do'", value: "half", tied: "end" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "re'", value: "eighth" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "do'", value: "half", tied: "start" },
      { type: "note", name: "do'", value: "half", tied: "end" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "half", dotted: true },
      { type: "rest", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "do", value: "half" },
      { type: "note", name: "do'", value: "half", tied: "start" },
      { type: "note", name: "do'", value: "half", tied: "end" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "re'", value: "eighth" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "do", value: "whole" },
    ],
  },
  {
    name: "Never Gonna Give You Up",
    author: "Rick Astley",
    startValue: 0.25,
    timeSignature: [2, 4],
    items: [
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "eighth", tied: "start" },
      { type: "note", name: "mi", value: "eighth", tied: "end" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "do", value: "quarter", tied: "start" },
      { type: "note", name: "do", value: "quarter", tied: "end" },
      { type: "rest", value: "quarter" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "half", tied: "end" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "eighth", tied: "end" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "do", value: "half" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "fa", value: "half", tied: "start" },
      { type: "note", name: "fa", value: "eighth", tied: "end" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "do", value: "quarter", tied: "start" },
      { type: "note", name: "do", value: "quarter", tied: "end" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "re", value: "eighth", tied: "start" },
      { type: "note", name: "re", value: "eighth", tied: "end" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "quarter", tied: "end" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "la", value: "eighth", dotted: true },
      { type: "note", name: "la", value: "sixteenth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "quarter", tied: "end" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "re", value: "eighth", dotted: true },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "eighth", tied: "start" },
      { type: "note", name: "mi", value: "sixteenth", tied: "end" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "la", value: "eighth", dotted: true },
      { type: "note", name: "la", value: "sixteenth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "quarter", tied: "end" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "sol", value: "eighth", dotted: true },
      { type: "note", name: "sol", value: "sixteenth", tied: "start" },
      { type: "note", name: "sol", value: "eighth", tied: "end" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "fa", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "la", value: "eighth", dotted: true },
      { type: "note", name: "la", value: "sixteenth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "quarter", tied: "end" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "mi", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "re", value: "eighth", dotted: true },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "mi", value: "sixteenth" },
      { type: "note", name: "do", value: "sixteenth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "eighth", tied: "start" },
      { type: "note", name: "mi", value: "sixteenth", tied: "end" },
      { type: "note", name: "re", value: "sixteenth" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
    ],
  },
  {
    name: "Amazing Grace",
    author: "John Newton",
    timeSignature: [3, 4],
    startValue: 0.5,
    items: [
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "si", value: "half" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "re", value: "half" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "quarter", dotted: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "re'", value: "half" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "re'", value: "eighth" },
      { type: "note", name: "re'", value: "half" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "quarter", dotted: true },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "re", value: "half" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "quarter", dotted: true },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
    ],
  },
  {
    name: "Bones in the ocean",
    author: "The Longest Johns",
    timeSignature: [3, 4],
    startValue: 0.5,
    items: [
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "do'", value: "eighth", tied: "start" },
      { type: "note", name: "do'", value: "quarter", tied: "end" },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "mi'", value: "eighth" },
      { type: "note", name: "re'", value: "eighth", tied: "start" },
      { type: "note", name: "re'", value: "quarter", tied: "end" },
      { type: "rest", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "quarter", tied: "end" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "eighth", tied: "start" },
      { type: "note", name: "si", value: "eighth", tied: "end" },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "sol", value: "eighth", tied: "start" },
      { type: "note", name: "sol", value: "quarter", tied: "end" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "re'", value: "eighth" },
      { type: "note", name: "mi'", value: "eighth", tied: "start" },
      { type: "note", name: "mi'", value: "quarter", tied: "end" },
      { type: "note", name: "re'", value: "eighth" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "si", value: "eighth" },
      { type: "note", name: "la", value: "eighth", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "si", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter", sharp: true },
      { type: "note", name: "sol", value: "quarter" },
      { type: "rest", value: "quarter" },
    ],
  },
  // Source: https://musescore.com/user/36854657/scores/6506983
  {
    name: "Becalmed",
    author: "Sea of Thieves",
    timeSignature: [3, 4],
    startValue: 0.5,
    items: [
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "fa", value: "half" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "si", value: "half", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "la", value: "quarter", dotted: true },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "fa", value: "quarter" },
      {
        type: "note",
        name: "re",
        value: "half",
        dotted: true,
        tied: "start",
      },
      { type: "note", name: "re", value: "half", tied: "end" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "do", value: "half" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "re'", value: "half" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "la", value: "half", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "re'", value: "half" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "half", dotted: true, tied: "start" },
      { type: "note", name: "sol", value: "quarter", tied: "end" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "half", flat: true, dotted: true },
      { type: "note", name: "la", value: "half", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "fa", value: "half", tied: "start" },
      { type: "note", name: "fa", value: "half", dotted: true, tied: "end" },
      { type: "note", name: "si", value: "half", dotted: true, flat: true },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "half", dotted: true, tied: "start" },
      { type: "note", name: "sol", value: "half", tied: "end" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "fa", value: "half" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "re'", value: "half" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "la", value: "half", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "la", value: "quarter", dotted: true },
      { type: "note", name: "si", value: "sixteenth", flat: true },
      { type: "note", name: "la", value: "sixteenth" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "half", dotted: true, tied: "start" },
      { type: "note", name: "fa", value: "half", tied: "end" },
    ],
  },
  // Source: https://www.youtube.com/watch?v=OeDM9nMew8Y
  {
    name: "Davy Jones",
    author: "Hans Zimmer",
    timeSignature: [3, 4],
    items: [
      { type: "note", name: "re", value: "half" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "fa", value: "half" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "do'", value: "eighth" },
      { type: "note", name: "si", value: "eighth", flat: true },
      { type: "note", name: "la", value: "half" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "do'", value: "half" },
      { type: "note", name: "re'", value: "eighth" },
      { type: "note", name: "si", value: "eighth", flat: true },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "la", value: "half", dotted: true },
      { type: "note", name: "si", value: "half", flat: true },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "si", value: "eighth", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "fa", value: "half" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "mi", value: "half" },
      { type: "note", name: "do", value: "quarter" },
      { type: "note", name: "do", value: "half" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "re", value: "half" },
      { type: "rest", value: "quarter" },
      { type: "note", name: "re", value: "half" },
      { type: "rest", value: "quarter" },
    ],
  },
  {
    name: "Age of Empires 2 Main theme",
    author: "Stephen Rippy",
    timeSignature: [4, 4],
    startValue: 0.75,
    items: [
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "sol", value: "half", tied: "start" },
      { type: "note", name: "sol", value: "eighth", tied: "end" },
      { type: "note", name: "si", value: "eighth", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "half", dotted: true },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "sol", value: "half", tied: "start" },
      { type: "note", name: "sol", value: "eighth", tied: "end" },
      { type: "note", name: "si", value: "eighth", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "do'", value: "half", dotted: true },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "sol", value: "half", tied: "start" },
      { type: "note", name: "sol", value: "eighth", tied: "end" },
      { type: "note", name: "si", value: "eighth", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "la", value: "half", tied: "start" },
      { type: "note", name: "la", value: "eighth", tied: "end" },
      { type: "note", name: "si", value: "eighth", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "sol", value: "half" },
    ],
  },
  // Source: https://www.youtube.com/watch?v=HmRdZg8cE4A
  {
    name: "A Whole New World",
    author: "Alan Menken",
    timeSignature: [4, 4],
    items: [
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "do", value: "half", dotted: true },
      { type: "rest", value: "quarter" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "sol", value: "half" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "eighth", sharp: true },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "re", value: "eighth" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "la", value: "eighth", tied: "start" },
      { type: "note", name: "la", value: "quarter", dotted: true, tied: "end" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "half", dotted: true },
      { type: "rest", value: "quarter" },
      { type: "rest", value: "quarter", dotted: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "eighth", flat: true, tied: "start" },
      {
        type: "note",
        name: "si",
        value: "quarter",
        flat: true,
        dotted: true,
        tied: "end",
      },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "la", value: "quarter", triplet: true },
      { type: "note", name: "si", value: "quarter", flat: true, triplet: true },
      { type: "note", name: "do'", value: "quarter", triplet: true },
      { type: "note", name: "mi'", value: "quarter" },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter", dotted: true },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi'", value: "quarter" },
      { type: "note", name: "fa'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter", dotted: true },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "re", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "half", dotted: true },
      { type: "rest", value: "quarter" },
      { type: "rest", value: "quarter", dotted: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "sol", value: "eighth" },
      { type: "note", name: "si", value: "eighth", flat: true, tied: "start" },
      {
        type: "note",
        name: "si",
        value: "quarter",
        flat: true,
        dotted: true,
        tied: "end",
      },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "la", value: "half" },
      { type: "note", name: "la", value: "quarter", triplet: true },
      { type: "note", name: "si", value: "quarter", flat: true, triplet: true },
      { type: "note", name: "do'", value: "quarter", triplet: true },
      { type: "note", name: "mi'", value: "quarter" },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "mi'", value: "quarter" },
      { type: "note", name: "fa'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter", dotted: true },
      { type: "note", name: "fa", value: "eighth" },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "la", value: "quarter" },
      { type: "note", name: "fa", value: "quarter" },
      { type: "note", name: "mi", value: "quarter" },
      { type: "note", name: "fa", value: "quarter", dotted: true },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "la", value: "eighth" },
      { type: "note", name: "si", value: "quarter", flat: true },
      { type: "note", name: "re'", value: "quarter" },
      { type: "note", name: "do'", value: "quarter", dotted: true },
      { type: "note", name: "do", value: "eighth" },
      { type: "note", name: "do'", value: "quarter" },
      { type: "note", name: "sol", value: "quarter" },
      { type: "note", name: "fa", value: "half", dotted: true },
      { type: "rest", value: "quarter" },
    ],
  },
  // {
  //   name: "Toss a coin to your Witcher",
  //   author: "Giona Ostinelli & Sonya Belousova",
  //   timeSignature: [4, 4],
  //   startValue: 0.5,
  //   items: [
  //     { type: "note", name: "sol", value: "eighth" },
  //     { type: "note", name: "fa", value: "eighth", sharp: true },
  //     { type: "note", name: "mi", value: "eighth" },
  //     { type: "note", name: "re", value: "eighth" },
  //     { type: "note", name: "mi", value: "half" },
  //     { type: "note", name: "la", value: "eighth" },
  //     { type: "note", name: "la", value: "eighth" },
  //     { type: "note", name: "sol", value: "eighth" },
  //     { type: "note", name: "fa", value: "eighth", sharp: true },
  //     { type: "note", name: "mi", value: "quarter", dotted: true },
  //     { type: "note", name: "mi", value: "eighth" },
  //     { type: "note", name: "la", value: "eighth" },
  //     { type: "note", name: "la", value: "eighth" },
  //     { type: "note", name: "si", value: "quarter" },
  //     { type: "note", name: "sol", value: "eighth" },
  //     { type: "note", name: "mi", value: "eighth", tied: "start" },
  //     { type: "note", name: "mi", value: "eighth", tied: "end" },
  //     { type: "note", name: "mi", value: "eighth" },
  //     { type: "note", name: "la", value: "quarter" },
  //     { type: "note", name: "sol", value: "quarter" },
  //     { type: "note", name: "la", value: "quarter" },
  //     { type: "note", name: "la", value: "eighth" },
  //     { type: "note", name: "si", value: "eighth" },
  //     { type: "note", name: "si", value: "quarter", tied: "start" },
  //     { type: "note", name: "si", value: "half", tied: "end" },
  //   ],
  // },
];
